#!/usr/bin/env python3
"""Collect Kakao place business hours for seeded gyms and emit update SQL."""

from __future__ import annotations

import argparse
import csv
import json
import re
import time
import urllib.error
import urllib.request
from pathlib import Path

from collect_kakao_gyms import sql_literal


KAKAO_PANEL_URL = "https://place-api.map.kakao.com/places/panel3"
DAY_KEYS = {
    "월": "mon",
    "화": "tue",
    "수": "wed",
    "목": "thu",
    "금": "fri",
    "토": "sat",
    "일": "sun",
}
DAY_ORDER = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
TIME_RE = re.compile(r"(\d{1,2}):(\d{2})")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Collect business hours from Kakao place panel3.")
    parser.add_argument("--input-csv", default="ops/gym-import/output-researched/kakao-gyms-researched.csv")
    parser.add_argument("--output-dir", default="ops/gym-import/output-business-hours")
    parser.add_argument("--sleep-seconds", type=float, default=0.12)
    parser.add_argument("--limit", type=int, default=0)
    return parser.parse_args()


def fetch_panel(kakao_id: str) -> dict:
    url = f"{KAKAO_PANEL_URL}/{kakao_id}"
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/json, text/plain, */*",
            "Origin": "https://place.map.kakao.com",
            "Referer": f"https://place.map.kakao.com/{kakao_id}",
            "User-Agent": "Mozilla/5.0",
            "appVersion": "6.6.0",
            "pf": "PC",
        },
    )
    last_error: Exception | None = None
    for attempt in range(1, 4):
        try:
            with urllib.request.urlopen(req, timeout=20) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError:
            raise
        except (TimeoutError, urllib.error.URLError) as exc:
            last_error = exc
            if attempt == 3:
                break
            time.sleep(attempt * 1.5)
    print(f"warning: skipped kakao_id={kakao_id} after retries ({last_error})")
    return {}


def parse_time_range(text: str) -> tuple[str, str] | None:
    times = TIME_RE.findall(text or "")
    if len(times) < 2:
        return None
    start = f"{int(times[0][0]):02d}:{times[0][1]}"
    end = f"{int(times[1][0]):02d}:{times[1][1]}"
    return start, end


def day_keys(day_text: str) -> list[str]:
    text = day_text or ""
    if text in ("매일", "매주"):
        return DAY_ORDER[:]
    if text in ("평일", "주중"):
        return ["mon", "tue", "wed", "thu", "fri"]
    if text == "주말":
        return ["sat", "sun"]
    matched = []
    for korean_day, key in DAY_KEYS.items():
        if korean_day in text:
            matched.append(key)
    return matched


def extract_business_hours(panel: dict) -> tuple[dict[str, dict[str, str]], list[dict]]:
    periods = (((panel.get("open_hours") or {}).get("all") or {}).get("periods") or [])
    result: dict[str, dict[str, str]] = {}
    sources = []
    for period in periods:
        title = period.get("period_title") or ""
        if "공휴일" in title:
            continue
        for day in period.get("days") or []:
            desc = ((day.get("on_days") or {}).get("start_end_time_desc") or "").strip()
            parsed = parse_time_range(desc)
            if not parsed:
                continue
            keys = day_keys(day.get("day_of_the_week") or "")
            if not keys:
                continue
            hours = {"open": parsed[0], "close": parsed[1]}
            for key in keys:
                result.setdefault(key, hours)
            sources.append({
                "period_title": title,
                "day": day.get("day_of_the_week"),
                "time": desc,
            })
    return {key: result[key] for key in DAY_ORDER if key in result}, sources


def write_csv(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        fieldnames = ["id", "kakao_id", "name", "business_hours", "source"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({
                "id": row["id"],
                "kakao_id": row["kakao_id"],
                "name": row["name"],
                "business_hours": json.dumps(row["business_hours"], ensure_ascii=False, separators=(",", ":")),
                "source": json.dumps(row["source"], ensure_ascii=False, separators=(",", ":")),
            })


def write_update_sql(path: Path, rows: list[dict]) -> None:
    lines = [
        "-- Generated by ops/gym-import/collect_kakao_business_hours.py",
        "-- Purpose: update gyms.business_hours JSONB from Kakao place open_hours.",
        "",
        "BEGIN;",
        "",
    ]
    for row in rows:
        payload = json.dumps(row["business_hours"], ensure_ascii=False, separators=(",", ":"))
        lines.append(
            "UPDATE gyms "
            f"SET business_hours = {sql_literal(payload)}::jsonb, updated_at = NOW() "
            f"WHERE id = {int(row['id'])} AND name = {sql_literal(row['name'])};"
        )
    lines.extend(["", "COMMIT;", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_verify_sql(path: Path) -> None:
    path.write_text(
        "\n".join([
            "SELECT",
            "  COUNT(*) AS gyms,",
            "  COUNT(*) FILTER (WHERE business_hours IS NOT NULL) AS gyms_with_business_hours,",
            "  COUNT(*) FILTER (WHERE business_hours IS NULL) AS gyms_without_business_hours",
            "FROM gyms",
            "WHERE status = 'active' AND deleted_at IS NULL;",
            "",
            "SELECT id, name, business_hours",
            "FROM gyms",
            "WHERE status = 'active' AND deleted_at IS NULL AND business_hours IS NOT NULL",
            "ORDER BY id",
            "LIMIT 10;",
            "",
        ]),
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    input_rows = list(csv.DictReader(open(args.input_csv, encoding="utf-8")))
    if args.limit:
        input_rows = input_rows[:args.limit]

    kept = []
    rejected = []
    raw_open_hours = {}
    for index, row in enumerate(input_rows, start=1):
        panel = fetch_panel(row["kakao_id"])
        open_hours = panel.get("open_hours")
        if open_hours:
            raw_open_hours[row["kakao_id"]] = open_hours
        business_hours, source = extract_business_hours(panel)
        if business_hours:
            kept.append({**row, "business_hours": business_hours, "source": source})
        else:
            rejected.append(row)
        if index % 10 == 0:
            print(f"searched {index}/{len(input_rows)} kept={len(kept)} rejected={len(rejected)}")
        time.sleep(args.sleep_seconds)

    write_csv(output_dir / "kakao-business-hours.csv", kept)
    (output_dir / "kakao-open-hours-raw.json").write_text(
        json.dumps(raw_open_hours, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    write_update_sql(output_dir / "05-update-production-business-hours.sql", kept)
    write_verify_sql(output_dir / "06-verify-production-business-hours.sql")
    summary = {
        "input_gyms": len(input_rows),
        "gyms_with_business_hours": len(kept),
        "gyms_without_business_hours": len(rejected),
        "output_dir": str(output_dir),
    }
    (output_dir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
